### ISSUE TITLE
Hard to switch to HDMI 2

### ISSUE THREAD

**Issue by AntonyPG** [amosstorkey/virgintivocec#3]
I have the Tivo connected to HDMI 1, and an Apple TV connected to HDMI 2. When I change to HDMI 2 the TV keeps switching between both devices for a few seconds, and sometimes goes back to HDMI 1. This wasn't a problem before introducing the Pi and the USB-CEC controller.

The Red/Yellow and Green/Blue buttons on the remote were mapped wrong, I changed these around in the main.cpp code.

I added the following line in the main.cpp code to allow the HOME button on the Panasonic remote to call up "My Shows":

 virginMap[CEC_USER_CONTROL_CODE_SETUP_MENU] = "TELEPORT NOWPLAYING\r\n";

**Comment by mbaggins** [comment]
I have had to put a cec less device on my apple tv 4k. Even with the cec setting turned off, if I have cec turned on on the TV, then it always tried to switch to appleTV. ALWAYS. I got a hdmi dongle thing that doesn't connect pin 13 and this has solved it. I have to manually change to apple tv on my receiver - but that's fine. 

with my TV if I enabled cec on all the devices, then they all come on when I turn the tv on (and the receiver comes on) and then they all fight to be the active channel. So I have cec on on the tv, on the receiver, with pulse 8 on the virgin - this allows me to then change the receiver to whatever source I want, and when I turn them off it automatically switches back to Virgin. Not perfect but works great for my needs. 

I think the Apple TV is at fault rather than anything else, even if you turn cec off on it, it is still on.

**Comment by amosstorkey** [comment]
Sadly there are many devices that fail to do CEC properly. Some of this is because people complain when they do the correct thing, and so they feel they have to simply. Others are simply that certain companies have had scant regard for compliance. The best TV I ever had for CEC was an older Samsung TV. But when I bought a more recent one, it ditched key parts of CEC making it a pain. My experience is that Blu-ray etc drives and apple devices are often over-agressive about requesting control, and TV's lack the settings for low level control of what they should do in response to different CEC settings. 

I am not sure if there is a fix request in any of the above - I don't think so, but thanks for the info.
